name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'

      - name: Build
        run: |
          go mod tidy
          go mod vendor
          go build managesw-mcp.go

      - name: Create tarball
        run: tar -czvf managesw-mcp.tar.gz managesw-mcp

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: managesw-mcp.tar.gz
