name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'

      - name: Build
        run: go build -o managesw-mcp -mod=vendor .

      - name: Create tarball
        run: tar -czvf managesw-mcp.tar.gz managesw-mcp

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: managesw-mcp.tar.gz
